### ISSUE TITLE
[HAL] Add uart functionality

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#10]
See header.

**Comment by trylimits** [comment]
Goal until wednesday:

UART (Step by step). Output nice2have

**Comment by wake-0** [comment]
Please review @trylimits. Normally I don't like so many comments but in this methods i think its necessary for maintainability.

**Comment by trylimits** [comment]
Looks good at first glance, however, I really think that `UART0-5` shouldn't be wrapped into an `enum`. The interface should provide something like `UARTGetUartCount()` similar to gpio/led, bc not every device has 6 UARTs. The number of UARTs is device-dependant and therefore should NOT be part of the general HAL interface.

Btw. Comments usually are a good thing :)

**Comment by trylimits** [comment]
Why is this still open? Further work to do?

**Comment by trylimits** [comment]
Finished and reviewed.
