### ISSUE TITLE
Get rid of the "test stuff" in main.c

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvOS#11]
We should clean up main.c. Atm there is still prototyping code from UART. This is not acceptable.

It should be cleaned up to:

```
int main(void) {
    while(1) { }
}
```

@mpe5651 Have you done that yesterday? If so, pls push, otherwise I will take this in the afternoon.

**Comment by ghost** [comment]
I've already cleaned it up. But I'm not able to push until I get home at approx. 19pm.
Hope you don't need a clean main right away.

**Comment by wake-0** [comment]
Does anyone need the remaining methods and defines in the main.c? @trylimits @mpe5651

**Comment by trylimits** [comment]
See above commit. I moved all the main.c stuff to main_temp.txt in main src folder. main.c is cleaned to endless while-loop.
