### ISSUE TITLE
[Driver] Refactor driver names

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#21]
Refactor all driver file and function names.

E.g.
File.: uartDriver
Function: UARTDriverInit(...)

**Comment by trylimits** [comment]
Generally I would like to see conventions like this, however, I would suggest the following guidelines:

```
File: driver_uart.h/c
Function name: UARTDriverInit(..)
```

Also see @mpe5651 his timer driver.

**Comment by wake-0** [comment]
It sounds good. I changed the name of the uart, pls do the same for all other files. Also for files like driver_led.h so that we use the guideline. The same also makes sense for the hal. hal_uart.c

**Comment by trylimits** [comment]
Refactored all names. Further work on naming conventions should be handled in Bug #17
