### ISSUE TITLE
[General] Remove warnings

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#22]
Remove all warnings from the code, which are not necessary.

**Comment by trylimits** [comment]
Warnings are never necessary. We should try to get rid of all warnings.

**Comment by wake-0** [comment]
Sometimes warnings are bugs:
e.g.
// surpress compiler warning that default starting point is different
--diag_suppress=10063

This was meant by necessary --> you cannot remove this bug, only suppress

**Comment by trylimits** [comment]
@mpe5651 Most of the warnings come from hal_timer.c and driver_timer.c. I will take care of those warnings if you confirm.

**Comment by ghost** [comment]
most of the warnings caused by the interrupt and timer code are now solved
