### ISSUE TITLE
[ProcessManagement] Implement elf file loader

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#32]
See title.

**Comment by wake-0** [comment]
This is also part of the loader. What do you think guys @trylimits @mpe5651 ?
Bug #46

**Comment by trylimits** [comment]
For me this would be ok if we merge all those tickets. However, imo it would be cleaner if we would have the following concept:

1.) ELF loader loads code/data/...-segment
2.) Loader takes the data from the ELF loader puts it into memory and kicks the Scheduler/ProcessManager
3.) Scheduler/ProcessManager does the remaining work (existing code)

**Comment by wake-0** [comment]
Decided to use a bin format.
