### ISSUE TITLE
[ProcessManagement] Implement Process Manager

### ISSUE THREAD

**Issue by ghost** [Blackjack92/fhvOS#33]
A Process Manager should be responsible for managing the processes, i.e. process id, name, ...

**Comment by wake-0** [comment]
I think this issue can be closed because it was added to ussue #55, which is already closed.
Please verify @mpe5651 @trylimits .

**Comment by ghost** [comment]
you're right. we oversaw that there already is an open issue for the process manager.

**Comment by trylimits** [comment]
Not finished yet :(

**Comment by trylimits** [comment]
`ProcessManagerStartProcess` should return the new process id.

**Comment by trylimits** [comment]
This `SetProcessState(..)` function should not be provided by the Process Manager. Above commit gets rid of this function.

**Comment by trylimits** [comment]
The ProcessManager should provide `argc` and `argv` to the new process.

**Comment by trylimits** [comment]
Above commit implements the rest of the functionality of the process manager.

Important note @mpe5651 @Blackjack92: There should not be any interaction with the Scheduler itself regarding creating new and killing processes. For this purpose the API of the ProcessManager has to be used.
