### ISSUE TITLE
[MemoryManagement] Implement .asm exception handler for MMU dabt

### ISSUE THREAD

**Issue by ghost** [Blackjack92/fhvOS#42]

**Comment by wake-0** [comment]
In the header file coprocessor.h were some functions added, which don't have the prefix MMU is there any reason for this? @mpe5651 
Maybe it would also be possible to call them:
        extern void CoprocessorEnableMMU(void);
        extern void CoprocessorDisableMMU(void);

**Comment by ghost** [comment]
yes, there is one. functions without the "MMU" prefix are ones that can also be used in another context than the mmu. for example, the cache can be used without having a activated mmu.
