### ISSUE TITLE
[Loader] Implement Loader

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#46]
Implement a loader for a .hex or .elf. It would be better, when .elf file would be suppported. 
The .elf file is on the sd card. The loader gets the start address of the .elf file and the length of the file.
The loader calls scheduler start process for the loaded process and copies the program into RAM.

**Comment by trylimits** [comment]
The loader has to copy the entire program into the RAM. @mpe5651 Could you please clarify how this is done? I think this is closely related to the MMU stuff.

**Comment by trylimits** [comment]
Cleaned up the loader code and it's working fine.
