### ISSUE TITLE
[Console] Extend the set of accepted characters

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvOS#53]
The console should accept:
1. blank character
2. backspace
3. `"` character
4. `*` character
5. `|` character
6. `.` character
7. and some more...

**Comment by trylimits** [comment]
1.) and 3-5.) done

Backspace support has to be implemented by overriding `__backspace(..)` (see. http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0378d/Chdjigab.html )

**Comment by trylimits** [comment]
6.) done

**Comment by trylimits** [comment]
I found an issue in using the ` `character. If there is already an input hitting space will return from`scanf`.

**Comment by trylimits** [comment]
Above commits solves the `scanf` issue. It wasn't actually a bug in our implementation :) See http://stackoverflow.com/questions/1247989/how-do-you-allow-spaces-to-be-entered-using-scanf

**Comment by wake-0** [comment]
Which characters are missing at the moment?

**Comment by trylimits** [comment]
Backspace support for sure (but minor) and some other characters which we should add time after time (if needed). Marking this ticket as pending?

**Comment by trylimits** [comment]
The console should abort an empty input directly without making a system call.

**Comment by trylimits** [comment]
Above commits extends the set of accepted characters and fixed the bug of an empty input. However, we cannot get backspace support if we keep using `scanf` for the prompt input.

The current implementation can be considered a simple, working console which does not support:

1.) Backspace
2.) Command history (up down keys)
3.) Cursor movement

Overall we should consider to implement an advanced console. I will open a new ticket for this.
