### ISSUE TITLE
[Scheduler] [Process Management] Add meta information to processes

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvOS#55]
Either the scheduler or a process manager should manage a process's meta information, i.e. name, start time, status etc.

@mpe5651 @Blackjack92 Should we add this functionality to the scheduler itself or should we introduce a process manager which is associated with the scheduler?

**Comment by ghost** [comment]
I would prefer a process manager. I'll explain you my opinion tomorrow.

**Comment by wake-0** [comment]
i would also prefer a process manager. It would be the same as a taskmanager.

**Comment by trylimits** [comment]
@mpe5651 if i remember correctly this issue should be fixed completely. Could you please close this if I didn't miss something.

**Comment by ghost** [comment]
you're absolutely right, mr.  @trylimits  :-)
