### ISSUE TITLE
[Driver] SD card

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#56]
Implement a SD card driver, which can be used to "communicate" with the SD card.

**Comment by trylimits** [comment]
Information and programming model for the multimedia card (MMC) can be found in AM335x technical reference manual on page 3384.

It seems like accessing the SD card is a bunch of work. Discussion on Wednesday. Pending until then.

**Comment by wake-0** [comment]
Testcode in main:

```
DeviceManagerInit();
device_t uart = DeviceManagerGetDevice("UART0", 5);
ConsoleInit(uart);
printf("Hello \n");
device_t sdCard = DeviceManagerGetDevice("SDCARD", 6);
DeviceManagerInitDevice(sdCard);
DeviceManagerOpen(sdCard);
```

**Comment by wake-0** [comment]
@trylimits pls verify the new approach to return the mmcsdCardInfo from the sd card driver read function. So the driver knows nothing about the fat but the filemanager can easily use the existing fat implementation.

**Comment by trylimits** [comment]
This bug is related to #74.

**Comment by trylimits** [comment]
Seems to work well for the moment. Additional features can be discussed in new (more fine-grained) tickets.
