### ISSUE TITLE
[Kernel] Implement kernel functions

### ISSUE THREAD

**Issue by ghost** [Blackjack92/fhvOS#58]
The kernel should provide functions like:

1.) ~~`KernelGetUptime()`~~
3.) ~~`KernelExecute(char* command)`~~
4.) ~~`KernelInfo(...)`~~ should print info message, providing the same interface as `printf`
5.) ~~`KernelDebug(...)`~~ should print debug message
6.) ~~`KernelError(...)`~~ should print error message
7.) ~~`KernelTick(int)`~~ should count up the ticks by parameter (uptime)

**Comment by trylimits** [comment]
@mpe5651 @Blackjack92 I'm not sure about function 2.) Should the kernel really be responsible for managing the current working directory. Shouldn't we introduce some kind of `FileManager` which is responsible for this (and more ofc). Pls provide your oppinions.

**Comment by trylimits** [comment]
I have implemented `KernelTick(int)` which counts up the uptime ticks and returns the new value.

**Comment by trylimits** [comment]
Above commit implements `KernelInfo`, `KernelError` and `KernelDebug`. Those functions should be used to print to the console within the kernel functions. The interface is equivalent to the `printf` function, therefore something like below is possible:

```
KernelInfo("Variable i=%i\n", i);
```

The implemented functions also use a mutex to guarantee correct output.

**Comment by ghost** [comment]
am I right in the assumption that kernelExecute is for system calls? in that case, implementing this function is done simply by calling a swi with a a appropriate sysCall number.

**Comment by trylimits** [comment]
`KernelExecute` is meant to be a function which starts an external program/command, e.g. `KernelExecute("uptime");` starts an external or internal process which prints the uptime. Other examples are `KernelExecute("ls"),`KernelExecute("more <file>") etc. Actually `KernelExecute(..)` just searches for an executable in a specified folder and runs the corresponding program. At the moment we should compile some core processes into the kernel, such as `uptime`.

**Comment by trylimits** [comment]
I found an issue with the implemented functions for printing out debug/error/info stuff. These functions use a mutex to ensure ordered output, however, in some cases this weirdly freezes the kernel as most of these functions are called within interrupt handlers which should not be locked :)

**Comment by trylimits** [comment]
Above commit solves the mutex issue.

**Comment by wake-0** [comment]
I would appreciate the FileManager idea. Some instance should handle the current directory with the contained files.

**Comment by trylimits** [comment]
The print functions of the Kernel should be wrapped into some conditional statements to allow disabling debug and error output in release mode.

**Comment by trylimits** [comment]
Above commit introduces `#define`s in `kernel.c` which allow to control the output level of kernel messages.

**Comment by trylimits** [comment]
~~We should move the `KernelExecute(..)` function completely to the FileManager implementation.~~

Edit: Nope :)

**Comment by trylimits** [comment]
This ticket is solved.
