### ISSUE TITLE
[Driver] Implement Driver Manager

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvOS#6]
There should be something like a Driver Manager which handles all the drivers within the kernel.
Rough idea of the concept:

1.) We have x different drivers, each identified by a unique id (of type `uint8`, thus a max of 255 different devices)
2.) DriverManager "instantiates" all drivers and assigns their id
3.) In the kernel itself the drivers can be accessed e.g. like that: `Driver led1 = _drivermanager_getDriver(LED1)` whereby `LED1` is an exported constant by the DriverManager

How user applications, i.e. system API, interconnects with this concept can be discussed later.

**Comment by trylimits** [comment]
@Blackjack92 @mpe5651 Please verify the concept and/or feedback.

**Comment by wake-0** [comment]
sounds good for me. so the drivermanager knows each driver and is used like an provider which provides different drivers.

**Comment by trylimits** [comment]
Driver Manager is good enough for the moment. Working example

```
DeviceManagerInit();

int i = 0;
char* leds[] = { "LED0", "LED1", "LED2", "LED3" };
for (i = 0; i < 4; i++) {
    device_t led = DeviceManagerGetDevice(leds[i], 4);
    DeviceManagerOpen(led);
    DeviceManagerWrite(led, "1", 1);
}
```

Adaptions should be treated in another ticket.
