### ISSUE TITLE
[ProcessManager] Implement function which waits until a process finishes

### ISSUE THREAD

**Issue by ghost** [Blackjack92/fhvOS#79]

**Comment by wake-0** [comment]
See bug #74 File Manager.

**Comment by trylimits** [comment]
Concept for that should be discussed in more detail.

**Comment by trylimits** [comment]
Above commit implements the functionality to start a process in blocking/non-blocking mode.

Examples:

```
# hello &                      // Starts in non-blocking mode

# hello                        // Starts in blocking mode
```

**Comment by trylimits** [comment]
Further discussion of the concept and/or implementation in Bug #74
