### ISSUE TITLE
[Driver] Implement Driver for the Serial Communication

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#8]
Implement a driver for the Serial Communication, which implements the general driver "interface" and also add it to the Driver Manager.

**Comment by trylimits** [comment]
@Blackjack92 Pls give an update on this. I could do the driver implementation.

**Comment by trylimits** [comment]
Driver is finished. Driver should be added to the Device Manager.

**Comment by trylimits** [comment]
I have added the uart driver to the device manager. Working code snippet:

```
DeviceManagerInit();
device_t uart0 = DeviceManagerGetDevice("UART0", 5);
DeviceManagerOpen(uart0);
DeviceManagerWrite(uart0, "Hallo", 5);
```
