### ISSUE TITLE
[MemoryManager] Add functions to get free pages in a row

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#82]
This method should return a pointer to the first free page.

**Comment by wake-0** [comment]
Used for #46.

**Comment by ghost** [comment]
@trylimits the function you will need later is:

```
pageAddressPointer_t MemoryManagerGetFreePagesInProcessRegion(unsigned int pagesToReserve)
```

i'll leave this ticket open. close it when you don't need it anymore.

**Comment by wake-0** [comment]
@trylimits do you need this ticket anymore?

**Comment by trylimits** [comment]
This is needed for #46. We can close this as it is referenced in #46 anyway.
