### ISSUE TITLE
[HAL] Add Interrupt

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#9]
Add the interrupt stuff to the existing HAL. This stuff will be used e.g. from the Interrupt Driver.

**Comment by ghost** [comment]
I'll take care of it because I'm already working on the interrupt issue.

**Comment by trylimits** [comment]
Goal until Wed:

Interrupt step-by-step. Nice2have: Every 100ms an interrupt.

**Comment by ghost** [comment]
all functions needed for implementing module-specific interrupts are now implemented and tested
