### ISSUE TITLE
[FileManager] Indication of read access through USR1

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvOS#92]
We should implement read access to the MMC by blinking USR1. We should either let the FileManager handle this or the DMA interrupt in the driver.

**Comment by wake-0** [comment]
Is it possible that another instance as the FileManager makes a read? When this can happen the driver should handle the blink otherwise the FileManager.

**Comment by trylimits** [comment]
We should introduce a policy that each access to the file system has to be done through the File Manager. I agree, the FileManager should handle the device. The implementation should follow the standard we set in the Scheduler's implementation, i.e. the `FileManagerInit(..)` function gets a `device_t`.

**Comment by trylimits** [comment]
Above commit implements this feature. File Manager now indicates it's work through LED1.
