### ISSUE TITLE
[Console] Different colors for outputtypes (info, error, debug)

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#93]

**Comment by trylimits** [comment]
I agree this would be a nice feature. `KernelInfo` should however print in the default color.

**Comment by trylimits** [comment]
Commit looks good overall. However, `ConsoleChangeDisplayedInformationType` should not be public API.

**Comment by wake-0** [comment]
Refactored the code. Pls have a look @trylimits and close the ticket.

**Comment by trylimits** [comment]
I guess you got me wrong :)

The console should not provide API to change the color to debug/error/info. It should provide functions for changing the color.

Or is there any other reason why those functions should be public API?

**Comment by trylimits** [comment]
I did some testing with the implemented feature and I found a bug in the implementation:

![image](https://cloud.githubusercontent.com/assets/7002180/7896741/db8a61be-06c3-11e5-9071-247669878473.png)

Running the `ps` command (which uses `printf` output) uses the debug color for it's output (SBW = should be white). Imo the color changing is not done correctly. It should be done as follows:

```
... KernelDebug(..)
{
    Change color to green
    [...] Print the debug output
    Reset color to white
}
```

Atm we are changing the color but we are missing to reset it back.

**Comment by wake-0** [comment]
I do not want to change the color back because it is a lot of overhead. Normally you chose a KernelDebug, KernelInfo or KernelError to display something, so the color should be set always correctly.

**Comment by wake-0** [comment]
But you are right this change is necessary at the moment. I will commit this change.

**Comment by trylimits** [comment]
This statement is true only within the kernel. User processes share the same console but cannot use `Kernel...(..)` functions to output something. User processes have to use `printf(..)` which is not completely under our control. Resetting the color in `Kernel..(..)` functions is therefore absolutely necessary. The overhead of sending 7 characters is acceptable.

**Comment by wake-0** [comment]
Read commit above.

**Comment by trylimits** [comment]
Output color is set correctly now:

![image](https://cloud.githubusercontent.com/assets/7002180/7896978/ad1ebffc-06cb-11e5-9a90-d2179fd76ec1.png)

Some minor changes should still be done:

1.) The public API of the console should be `ConsoleColor(color_t)`
2.) Instead of calling `ConsoleDisplayInfo()` for resetting the color we should call `ConsoleColor(white)`

**Comment by trylimits** [comment]
As we just discussed:

I agree that `Kernelnfo(..)` should not print white. Blue would be a nice color for `KernelInfo(..)`.

**Comment by wake-0** [comment]
Maybe this would be a better style for displaying the different types (debug, error, info):

![unbenannt](https://cloud.githubusercontent.com/assets/11227428/7897098/ff6e4c6a-06cf-11e5-8890-29b51f6eeea7.PNG)

**Comment by trylimits** [comment]
I like the output as it is on master branch, i.e. the whole line is colored.

**Comment by trylimits** [comment]
@Blackjack92 What purpose has `KernelPrint(..)`? Imo we should refactor this to `KernelVerbose(..)` which makes more sense in the context of printing something system-relevant. I'll open a new ticket for that. See #97
